import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js + MUI!
        </h1>
        <p></p>


        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Web Nextjs &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://v4.mui.com/getting-started/installation/" className={styles.card}>
            <h2>Web MUI &rarr;</h2>
            <p>Material-UI, the worlds most popular React UI framework.</p>
          </a>

          <a
            href="https://github.com/biyonosirclo/next_mui"
            className={styles.card}
          >
            <h2>Github &rarr;</h2>
            <p>Download Project di github sekarang</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Hasil dari example githun yang sudah di deploy
            </p>
          </a>
        </div>
      </main>

    </div>
  )
}
